version: '3.8'

services:
  backend:
    build: ./backend
    container_name: integraite-backend
    ports:
      - "8000:8000"
    env_file:
      - .env  # ודאי שיש לך קובץ .env בתיקייה הראשית!
    volumes:
      - ./backend/app:/app/app # מאפשר Hot-Reload בפיתוח (שינוי קוד משתקף מיד)
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: integraite-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend # מחכה שהשרת יעלה לפני שהפרונט עולה
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    # בפיתוח, אנחנו רוצים להריץ את השרת של ריאקט, לא את הבילד הסטטי
    command: npm start